name: Juist
favicon: null
layout_spectrum: 0.7551898006349802
typography_spectrum: 0.73538
title: Juist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00aae4'
    - '#ffffff'
    - '#55c6ed'
    - '#ff0045'
    - '#ff4477'
  brandStrength: 0.6980912401340902
  lightness: 0.36790315015241504
  saturation: 0.637733836658299
  rhythmicContrast: 0.2666756238322705
purpose: []
